### ISSUE TITLE
HASTAC directory pages display incorrect header

### ISSUE THREAD

**Issue by babaklar** [mlaa/commons#688] opened 2023-07-18 19:46 UTC
When clicking on the pages for HASTAC [members](https://hastac.hcommons.org/members/), [groups,](https://hastac.hcommons.org/groups/) and [sites](https://hastac.hcommons.org/sites/), a large error message appears on the top of the screen. ![Screenshot 2023-07-18 at 1.08.27 PM.png](https://images.zenhubusercontent.com/62572e0e3e1b973699e0382a/bcd704ee-8f46-40d8-8fa2-748093fd9839)

**Comment by mikethicke** [comment] 2023-07-19 13:42
Ultimately this was addressed by rolling back BuddyPress to 10.6 . 

I couldn't find a discrepancy between staging and production that would account for this behavior. The underlying cause is a mystery to me as I couldn't reproduce in a dev environment, but from what I can tell it was loading page data from the wrong post id for buddypress pages. (Ie. groups had a post_id of 42, but it was loading content from post_id 6, which is an email template)

**Closed as completed by mikethicke** 2023-07-19 13:42 UTC
Labels: bug
